### ISSUE TITLE
Issue: Pumping window

### ISSUE THREAD

**Issue by mengsk09876** [OSU-CS361-W17/group18_project2#1]
I try to add the error function to the game, but I dont know how to add a pumping window as a auto issue of a error message.
I also want to add a function that alert user when they are closing the game page, 
here is the code of JS:
```
(function(){
    // while closing the window
    $(window).bind('beforeunload', function(){
        // only when variable is_confirm is not false
        if(window.is_confirm !== false)
            return 'Are you sure want to leave?';
    })
})();
```
 Its not working very well.
----------------------
I just found that its probably because the jQuery.

**Comment by j1298666** [comment]
I set the condition for fire button to make sure if any ship has been placed, and it would prompt out the alert window.
Just use the alert in app.js:
`        alert("You didn't place any ship!");
`
I might push my code later.
